# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-26 07:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tweet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(blank=True, max_length=200)),
                ('date_tweeted', models.CharField(blank=True, max_length=25)),
                ('tweet', models.CharField(blank=True, max_length=200)),
                ('location', models.CharField(blank=True, max_length=200)),
            ],
        ),
    ]
